resources:
  - ../../base

namePrefix: prod-

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: htmlsampleproject-deployment
  - path: service-patch.yaml
    target:
      kind: Service
      name: htmlsampleproject-service
